language: node_js

node_js:
  - "node"
  - "lts/*"
  - "8"
  - "6"

install:
  - "npm install"

script:
  - "npm run build"

deploy:
  skip_cleanup: true
  provider: npm
  email: "arylo.open@gmail.com"
  api_key: "${NPM_TOKEN}"
  on:
    branch: master
    node_js: "node"